from gensim.models import word2vec
model=word2vec.Word2Vec.load("./model_px.model")
print(f'-----乔峰的词向量为----')
print(model.wv['乔峰'])
print(f'-----张无忌的词向量为----')
print(model.wv['张无忌'])
print(f'-----郭靖的词向量为----')
print(model.wv['郭靖'])
print(f'-----罗辑----')
print(model.wv['郭靖'])
print(f'-----叶文洁----')
print(model.wv['叶文洁'])
print(f'-----杨过----')
print(model.wv['杨过'])

print(model.wv.most_similar("乔峰",topn=10))
print(model.wv.most_similar("张无忌",topn=10))
print(model.wv.most_similar("郭靖",topn=10))
print(model.wv.most_similar("罗辑",topn=10))
print(model.wv.most_similar("叶文洁",topn=10))
print(model.wv.most_similar("杨过",topn=10))
print(model.wv.most_similar("郭靖",topn=10))
print(model.wv.most_similar("令狐冲",topn=10))
